term="AdarovaAI"
name="Adarova A.I."
work="Medical Radiological Research Center named after A.F. Tsyb – branch of the Federal State Budgetary Institution \"National Medical Research Center of Radiology\" of the Ministry of Health of Russia"
full_name="Adarova Alevtina I."
regals="engineer"
email="alya.adarova@mail.ru"
