term="AndrianovaON"
name="Andrianova O.N."
work="JSC “All-Russian Research Institute for Nuclear Power Plants Operation”"
full_name="Andrianova Olga N."
regals="Chief Expert, Cand.Sci. (Engineering)"
email="ONAndrianova@vniiaes.ru"
