term="AskhadullinSR"
name="Askhadullin S.R."
work="IPPE JSC"
full_name="Askhadullin Sergey R."
regals="Researcher-Chemist-Analyst of the Laboratory of Chemical-Engineering and Radiochemical Research"
email="sraskhadullin@ippe.ru"
