term="BasovaMA"
name="Basova M.A."
work="Kurchatov Complex of Radiology and Agroecology of the NRC ‘‘Kurchatov Institute’’ (KK RAE)"
full_name="Basova Maria A."
regals="Junior Researcher"
email="maribasova97@mail.ru"
