term="BedrinovAA"
name="Bedrinov A.A."
work="Novovoronezh Nuclear Power Plant, Branch of \"Concern Rosenergoatom\""
full_name="Bedrinov Andrey A."
regals="Head of Department"
email="BedrinovAA@nvnpp1.rosenergoatom.ru"
