term="BeltyukovAI"
name="Bel’tyukov A.I."
work="Ural Federal University"
full_name="Bel’tyukov Aleksandr I."
regals="Associate Professor, Department of Nuclear Power Plants andRenewable Energy Sources, Cand. Sci. (Engineering)"
email="beltukovai@gmail.com"
