term="BlandinskiyVY"
name="Blandinskiy V.Y."
work="National Research Center «Kurchatov Institute»"
full_name="Blandinskiy Victor Yu."
regals="scientific secretary, Cand. Sci. (Engineering)"
email="Blandinskiy_VY@nrcki.ru"
