term="BokovaTA"
name="Bokova T.A."
work="Nizhny Novgorod State Technical University named after R.E. Alekseev"
full_name="Bokova Tatyana A."
regals="Associate Professor, Cand. Sci. (Engineering)"
email="tatabo@bk.ru"
