term="BryazginAA"
name="Bryazgin A.A."
work="Budker Institute of Nuclear Physics SB RAS"
full_name="Bryazgin Aleksandr A."
regals="leading researcher, Head of Laboratory, Cand. Sci. (Engineering)"
email="A.A.Bryazgin@inp.nsk.su"
