term="BudarinAA"
name="Budarin A.A."
work="JSC «Scientific-technical center «DIAPROM» (JSC «STCD»)"
full_name="Budarin Alexei A."
regals="Head of the department of technical diagnostics of reactor installations of various types"
email="budaa@diaprom.ru"
