term="BurukinAV"
name="Burukin A.V."
work="RIAR JSC"
full_name="Burukin Andrey V."
regals="Deputy Head for Science, Division \"Nuclear Research Reactors Complex\", Head of Physics and Power Engineering Department, Cand. Sci. (Engineering)"
email="burukin@niiar.ru"
