term="BytchkovVM"
name="Bytchkov V.M."
work="Independent expert"
full_name="Bytchkov Valerij M."
regals="independent expert in the area of nuclear safeguards and nonproliferation, Cand. Sci. (Phys.-Math.)"
email="valeri.bytchkov@gmail.com"
