term="ChugunovAS"
name="Chugunov A.S."
work="Saint-Petersburg State Institute of Technology (Technical University)"
full_name="Chugunov Aleksandr S."
regals="senior researcher of the department of engineering radioecology and radiochemical technology, Cand. Sci. (Chem.)"
email="tchugunov@mail.ru"
