term="DanilovaDR"
name="Danilova D.R."
work="JSC Polzunov Scientific and Production Association for the Research and Design of Power Equipment"
full_name="Danilova Daria R."
regals="Technic"
email="DanilovaDR@ckti.ru"
