term="DmitrievSM"
name="Dmitriev S.M."
work="Nizhny Novgorod State Technical University n.a. R.E. Alekseev"
full_name="Dmitriev Sergey M."
regals="Rector, Professor, Doc. Sci. (Engineering)"
email="dmitriev@nntu.ru"
