term="DornYA"
name="Dorn Y.A."
work="Russian Institute of Radiology and Agroecology of National Research Centre \"Kurchatov Institute\""
full_name="Dorn Yulia A."
regals="chief specialist"
email="julya.dorn@yandex.ru"
