term="DoronkovDV"
name="Doronkov D.V."
work="Nizhny Novgorod State Technical University n.a. R.E. Alekseev"
full_name="Doronkov Denis V."
regals="Senior research fellow, Cand. Sci. (Engineering)"
email="nevid000@mail.ru"
