term="DruzhininVE"
name="Druzhinin V.E."
work="JSC “All-Russian Research Institute for Nuclear Power Plants Operation”"
full_name="Druzhinin Vladimir E."
regals="Head of Department, Cand. Sci. (Engineering)"

