term="DvornikovPA"
name="Dvornikov P.A."
work="JSC “Scientific and Technical Center “DIAPROM” (JSC “STCD”)"
full_name="Dvornikov Pavel A."
regals="Research supervisor, Dr. Sci. (Engineering)"
email="dvornikov@diaprom.ru"
