term="FarakshinMR"
name="Farakshin M.R."
work="Afrikantov OKBM JSC"
full_name="Farakshin Mansur R."
regals="Head of Department of the BN Reactor Core Development, Cand. Sci. (Engineering)"
email="farakshin@okbm.nnov.ru"
authorid="883340"
