term="FomichevVV"
name="Fomichev V.V."
work="Karpov Research and Development Institute for Physical Chemistry, JSC"
full_name="Fomichev Vladimir V."
regals="head of department"
email="Vovik19931993@mail.ru"
