term="GlazyukYV"
name="Glazyuk Y.V."
work="NIKIET JSC"
full_name="Glazyuk Yakov V."
regals="Deputy general director, Chief designer of neutron physics parameter monitoring equipment"
email="jackov@nikiet.ru"
