term="IvanovIE"
name="Ivanov I.E."
work="JSC “All-Russian Research Institute for Nuclear Power Plants Operation”"
full_name="Ivanov Ilya E."
regals="Leading Researcher, Cand. Sci. (Phys.-Math.)"
email="IEIvanov@vniiaes.ru"
