term="KaluginMA"
name="Kalugin M.A."
work="NRC «Kurchatov Institute»"
full_name="Kalugin Mikhail A."
regals="Deputy Head of the complex for scientific work, Dr. Sci. (Engineering)"
email="Kalugin_MA@nrcki.ru"
