term="KarandeevaNV"
name="Karandeeva N.V."
work="State Atomic Energy Corporation Rosatom"
full_name="Karandeeva Natalia V."
regals="Chemical Engineer (operation manual)"
email="KarandeevaNV@nvnpp1.rosenergoatom.ru"
