term="KarpenkoAI"
name="Karpenko A.I."
work="Ural Federal University"
full_name="Karpenko Anatoly I."
regals="Professor, Nuclear Power Plants and Renewable Energy Sources Department Dr. Sci. (Engineering)"

