term="KlimovaVA"
name="Klimova V.A."
work="Ural Federal University"
full_name="Klimova Victoria Andreevna"
regals="Senior Lecturer of the Nuclear Power Plants and Renewable Energy Sources Department"
email="v.a.klimova@urfu.ru"