term="KlinovDA"
name="Klinov D.A."
work="JSC «SSC RF-IPPE n.a. A.I. Leypunsky»"
full_name="Klinov Dmitri Anatolievich"
regals="Deputy Scientific Director for Promising Topics, Cand. Sci. (Engineering)"
email="dklinov@ippe.ru"