term="KochnovOY"
name="Kochnov O.Yu."
work="Karpov Research and Development Institute for Physical Chemistry, JSC"
full_name="Kochnov Oleg Yu."
regals="chief engineer, Dr. Sci. (Engineering)"
email="kochnov2000@mail.ru"
