term="KochnovOY"
name="Kochnov O.Y."
work="Karpov Research and Development Institute for Physical Chemistry, JSC"
full_name="Kochnov Oleg Yu."
regals="chief engineer, professor, Dr. Sci. (Engineering)"
email="kochnov@karpovipc.ru"
