term="KolesovVV"
name="Kolesov V.V."
work="Karpov Research and Development Institute for Physical Chemistry, JSC"
full_name="Kolesov Valery V."
regals="engineer of 1 category, Cand. Sci. (Phys.-Math.)"
email="kolesov@iate.obninsk.ru"
