term="KovtunSN"
name="Kovtun S.N."
work="JSC “Scientific and Technical Center “DIAPROM” (JSC “STCD”)"
full_name="Kovtun Sergey N."
regals="Head of the service for the development of special diagnostic systems, Cand. Sci. (Engineering)"
email="skov@diaprom.ru"
