term="KozminGV"
name="Kozmin G.V."
work="Kurchatov Complex of Radiology and Agroecology of the NRC ‘‘Kurchatov Institute’’ (KK RAE)"
full_name="Kozmin Gennady V."
regals="Leading Researcher, Cand. Sci. (Biology)"
email="kozmin@obninsk.ru"
