term="KryukovAN"
name="Kryukov A.N."
work="Afrikantov OKBM JSC"
full_name="Kryukov Aleksander N."
regals="Deputy Chief Designer of BN Reactor Plants"
email="ankrukov@okbm.nnov.ru"
authorid="1280123"
spin="4619-8065"
