term="KudryaevAA"
name="Kudryaev A.A."
work="JSC “Scientific and Technical Center “DIAPROM” (JSC “STCD”)"
full_name="Kudryaev Andrey A."
regals="First deputy general director-technical director"
email="kudryaev@diaprom.ru"
