term="KulakovEN"
name="Kulakov E.N."
work="JSC Polzunov Scientific and Production Association for the Research and Design of Power Equipment"
full_name="Kulakov Egor N."
regals="Engineer"
email="KulakovEN@ckti.ru"
