term="KurachenkoYA"
name="Kurachenko Y.A."
work="IPPE JSC"
full_name="Kurachenko Yurij A."
regals="leading specialist in the field of radiation transfer theory, Dr. Sci.(Phys.-Math.)"
email="yuakurachenko@ippe.ru"
