term="KuzenkovaDS"
name="Kuzenkova D.S."
work="National Research Center «Kurchatov Institute»"
full_name="Kuzenkova Daria S."
regals="senior researcher, Cand. Sci. (Engineering)"
email="Kuzenkova_DS@nrcki.ru"
