term="KuznetsovNV"
name="Kuznetsov N.V."
work="Karpov Research and Development Institute for Physical Chemistry, JSC"
full_name="Kuznetsov Nikita V."
regals="head of department"
email="kuznetsov@karpovipc.ru"
