term="LegenkijAA"
name="Legen’kij A.A."
work="Proryv JSC"
full_name="Legen’kij Aleksandr A."
regals="Chief Specialist of the Responsibility Center of R&D on On-SiteNuclear Fuel Cycle of the Proryv Project"
email="leaa@pnproryv.ru"
