term="LisyanskiiAS"
name="Lisyanskii A.S."
work="JSC Polzunov Scientific and Production Association for the Research and Design of Power Equipment"
full_name="Lisyanskii Alexander S."
regals="Advisor to the General Director, Dr. Sci. (Engineering)"
email="LisianskiiAS@ckti.ru"
