term="LizorkinMP"
name="Lizorkin M.P."
work="NRC «Kurchatov Institute»"
full_name="Lizorkin Mikhail P."
regals="Head of the VVER Physics Division, Dr. Sci. (Engineering)"
email="Lizorkin_MP@nrcki.ru"
