term="LukyanovDA"
name="Lukyanov D.A."
work="JSC “Scientific and Technical Center “DIAPROM” (JSC “STCD”)"
full_name="Lukyanov Dmitry A."
regals="Head of the special purpose systems development department, Cand. Sci. (Engineering)"
email="dluk@diaprom.ru"
