term="MedetbekovBS"
name="Medetbekov B.S."
work="Institute of Atomic Energy of the National Nuclear Center of the Republic of Kazakhstan"
full_name="Medetbekov Berik S."
regals="Junior Researcher"
email="medetbekov@nnc.kz"
