term="MelnikovaTV"
name="Melnikova T.V."
work="IATE MEPhI, MEPhI"
full_name="Melnikova Tatiana V."
regals="Associate Professor, Department of Nuclear Physics and Technology, Cand. Sci. (Chemistry)"
email="tritel2010@gmail.com"
