term="MikhailenkoMA"
name="Mikhailenko M.A."
work="Institute of Solid Stat Chemistry and Mechanochemistry SB RAS"
full_name="Mikhailenko Mikhail A."
regals="senior researcher, Cand. Sci. (Chemistry)"
email="mikhailenko@solid.nsc.ru"
