term="MolyavkinAN"
name="Molyavkin A.N."
work="JSC “Scientific and Technical Center “DIAPROM” (JSC “STCD”)"
full_name="Molyavkin Aleksej N."
regals="Deputy technical director for the development of diagnostic systems – head of the department of diagnostics of reactor installations"
email="molyavkin@diaprom.ru"
