term="MosunovaNA"
name="Mosunova N.A."
work="Nuclear Safety Institute of the Russian Academy of Sciences (IBRAE RAN)"
full_name="Mosunova Nastasia A."
regals="Deputy Director, Dr. Sci. (Engineering)"
email="nam@ibrae.ac.ru"
