term="MysinKS"
name="Mysin K.S."
work="Branch of JSC Rosenegroatom Concern, Novovoronezh Nuclear Power Plant"
full_name="Mysin Konstantin S."
regals="Shift supervisor of Unit 6"
email="MysinKS@nvnpp1.rosenergoatom.ru"
