term="NepogodinaYV"
name="Nepogodina Y.V."
work="IATE MEPhI"
full_name="Nepogodina Yana V."
regals="Postgraduate student, Department of Nuclear Physics and Technology"
email="dragonflynepogodina@gmail.com"
