term="OshkanovNN"
name="Oshkanov N.N."
work="Ural Federal University"
full_name="Oshkanov Nikolay N."
regals="Professor, Department of Nuclear Power Plants and RenewableEnergy Sources, Cand. Sci. (Engineering)"
email="n.n.oshkanov@urfu.ru"
