term="OzrinVD"
name="Ozrin V.D."
work="Nuclear Safety Institute of the Russian Academy of Sciences (IBRAE RAN)"
full_name="Ozrin Vladimir D."
regals="senior researcher, Cand. Sci. (Phys.-Math.)"
email="ozrin@ibrae.ac.ru"
