term="PakholikDA"
name="Pakholik D.A."
work="Karpov Research and Development Institute for Physical Chemistry, JSC"
full_name="Pakholik Denis A."
regals="leading engineer-physicist"
email="pakholikda@mail.ru"
