term="PavlovAN"
name="Pavlov A.N."
work="Russian Institute of Radiology and Agroecology of National Research Centre \"Kurchatov Institute\""
full_name="Pavlov Alexander N."
regals="senior researcher, Cand. Sci. (Biological)"
email="49434@mail.ru"
