term="PeregudovAA"
name="Peregudov A.A."
work="IPPE JSC"
full_name="Peregudov Anton A."
regals="Head of Department of Calculated Safety Research of NPP, Cand. Sci. (Engineering)"
email="aperegudov@ippe.ru"
