term="PogorelovMD"
name="Pogorelov M.D."
work="Nizhny Novgorod State Technical University named after R.E. Alekseev"
full_name="Pogorelov Mikhail D."
regals="Assistant"
email="md.pogorelov@yandex.ru"
