term="PolozkovSD"
name="Polozkov S.D."
work="National Research Tomsk Polytechnic University, Novovoronezh Nuclear Power Plant, Branch of Rosenergoatom Concern JSC, Russia"
full_name="Polozkov Sergey D."
regals="postgraduate student, engineer of the nuclear safety and reliability department"
email="polozkovSD@nvnpp1.rosenergoatom.ru"
