term="PopovAV"
name="Popov A.V."
work="JSC Polzunov Scientific and Production Association for the Research and Design of Power Equipment"
full_name="Popov Aleksey V."
regals="Engineer"
email="PopovAV@ckti.ru"
