term="PopovYA"
name="Popov Y.A."
work="Institute of Atomic Energy of the National Nuclear Center of the Republic of Kazakhstan"
full_name="Popov Yuri A."
regals="Deputy Head of Laboratory"
email="Popov@nnc.kz"
