term="PovarovPV"
name="Povarov P.V."
work="Branch of JSC Rosenegroatom Concern, Novovoronezh Nuclear Power Plant"
full_name="Povarov Peter V."
regals="Head of Reactor Shop No. 6"
email="PovarovPV@nvnpp1.rosenergoatom.ru"
