term="ProzorovaIV"
name="Prozorova I.V."
work="Institute of Atomic Energy of the National Nuclear Center of the Republic of Kazakhstan, National Research Tomsk Polytechnic University"
full_name="Prozorova Irina V."
regals="Head of Laboratory"
email="Prozorova@nnc.kz"
