term="RogozhkinSA"
name="Rogozhkin S.A."
work="Afrikantov OKBM JSC"
full_name="Rogozhkin Sergey A."
regals="Chief Designer of BN Reactor Plants, Cand. Sci. (Engineering)"
email="rogozhkin@okbm.nnov.ru"
