term="SabitovaRR"
name="Sabitova R.R."
work="Institute of Atomic Energy of the National Nuclear Center of the Republic of Kazakhstan"
full_name="Sabitova Radmila R."
regals="Junior Researcher"
email="sabitovar@nnc.kz"
