term="SamoilovOB"
name="Samoilov O.B."
work="JSC «OKBM Afrikantov»"
full_name="Samoilov Oleg B."
regals="General director’s council, Professor, Doc. Sci. (Engineering)"
email="dep48_teplofiz@okbm.nnov.ru"
