term="SavchitsSM"
name="Savchits S.M."
work="Proryv JSC"
full_name="Savchits Sergey M."
regals="Chief Design Officer - Head of the Responsibility Center of R&D on On-Site Nuclear Fuel Cycle of the Proryv Project"
email="savchitssm@pnproryv.ru"
