term="SavinovAA"
name="Savinov A.A."
work="JSC “Scientific and Technical Center “DIAPROM” (JSC “STCD”)"
full_name="Savinov Andrey A."
regals="Head of the sensor development laboratory"
email="savinov@diaprom.ru"
