term="ShablovVL"
name="Shablov V.L."
work="OINPE MEPhI"
full_name="Shablov Vladimir L."
regals="Professor, Department of Nuclear Physics and Technology, Dr. Sci. (Phys.-Math.)"
email="shablov.vl@yandex.ru"
