term="ShchekleinSE"
name="Shcheklein S.E."
work="Ural Federal University"
full_name="Shcheklein Sergey E."
regals="Head of the Nuclear Power Plants and Renewable Energy Sources Department, Dr. Sci. (Engineering)"
email="s.e.shcheklein@urfu.ru"
