term="ShchekleinSE"
name="Shcheklein S.E."
work="Ural Federal University"
full_name="Shcheklein Sergei E."
regals="Dr. Sci. (Engineering), Professor, head of the Nuclear Power Plants and Renewable Energy Sources Department"
email="s.e.shcheklein@urfu.ru"
