term="ShepelevSF"
name="Shepelev S.F."
work="Afrikantov OKBM JSC"
full_name="Shepelev Sergey F."
regals="Advisor to the General Director for BN Reactor Plants, Cand. Sci.(Engineering)"
email="shepelev@okbm.nnov.ru"
