term="ShutikovAV"
name="Shutikov A.V."
work="JSC Rosenergoatom Concern"
full_name="Shutikov Alexander V."
regals="General Director of Rosenergoatom Concern JSC, Cand. Sci.(Engineering)"
email="info@rosenergoatom.ru"
