term="ShutovPS"
name="Shutov P.S."
work="JSC «Scientific-technical center «DIAPROM» (JSC «STCD»)"
full_name="Shutov Pavel S."
regals="Deputy Head of the department of technical diagnostics of reactor installations of various types"
email="shutovps@diaprom.ru"
