term="SidorovII"
name="Sidorov I.I."
work="Beloyarsk NPP"
full_name="Sidorov Ivan I."
regals="Deputy General Director – Director of Beloyarsk Nuclear Power Plant Branch of JSC Concern Rosenergoatom"
email="info@rosenergoatom.ru"
