term="SnegirevAS"
name="Snegirev A.S."
work="Kurchatov Complex of Radiology and Agroecology of the NRC ‘‘Kurchatov Institute’’ (KK RAE)"
full_name="Snegirev Aleksei S."
regals="Junior Researcher, Cand. Sci. (Biology)"
email="snegir.05@mail.ru"
