term="SorokinAnA"
name="Sorokin A.A."
work="Nuclear Safety Institute of the Russian Academy of Sciences (IBRAE RAN)"
full_name="Sorokin Andrey A."
regals="senior researcher, Cand. Sci. (Phys.-Math.)"
email="sorokin@ibrae.ac.ru"
