term="SpiridonovSI"
name="Spiridonov S.I."
work="NRC “Kurchatov Institute“ – RIRAE"
full_name="Spiridonov Sergei I."
regals="chief researcher, Dr. Sci. (Biology), professor"
email="spiridonov.si@gmail.com"
