term="StaroverovAI"
name="Staroverov A.I."
work="Afrikantov OKBM JSC"
full_name="Staroverov Alexander I."
regals="Deputy Chief Designer of Afrikantov Design Bureau, Dr. Sci. (Engineering)"
email="info@okbm.ru"
