term="SubbotinSA"
name="Subbotin S.A."
work="National Research Center «Kurchatov Institute»"
full_name="Subbotin Stanislav A."
regals="Head of Department, Cand. Sci. (Engineering)"
email="Subbotin_SA@nrcki.ru"
