term="SvetachevSN"
name="Svetachev S.N."
work="Institute of Atomic Energy of the National Nuclear Center of the Republic of Kazakhstan"
full_name="Svetachev Stanislav N."
regals="Engineer"
email="svetach@nnc.kz"
