term="SvyatkinFA"
name="Svyatkin F.A."
work="JSC Polzunov Scientific and Production Association for the Research and Design of Power Equipment"
full_name="Svyatkin Fyodor A."
regals="Head of Heat Exchange Equipment Department"
email="SvyatkinFA@ckti.ru"
