term="TarasovOV"
name="Tarasov O.V."
work="Nuclear Safety Institute of the Russian Academy of Sciences (IBRAE RAN)"
full_name="Tarasov Oleg V."
regals="senior researcher, Cand. Sci. (Phys.-Math.)"
email="olegtarasov79@gmail.com"
