term="TashlykovOL"
name="Tashlykov O.L."
work="Ural Federal University"
full_name="Tashlykov Oleg L."
regals="Dr. Sci. (Engineering), Professor of the Nuclear Power Plants and Renewable Energy Sources Department"
email="otashlykov@list.ru"
