term="TashlykovOL"
name="Tashlykov O.L."
work="Ural Federal University"
full_name="Tashlykov Oleg L."
regals="Professor of the Nuclear Power Plants and Renewable Energy SourcesDepartment, Dr. Sci. (Engineering)"
email="o.l.tashlykov@urfu.ru"
