term="TerekhovSV"
name="Terekhov S.V."
work="A.A. Galkin Donetsk Institute of Physics and Technology"
full_name="Terekhov Sergey V."
regals="leading researcher, Dr. Sci. (Phys.-Math.)"
email="svlter@yandex.ru"
