term="TkachenkoVO"
name="Tkachenko V.O."
work="Budker Institute of Nuclear Physics SB RAS"
full_name="Tkachenko Vadim O."
regals="senior researcher, Cand. Sci. (Engineering)"
email="vtkachen@mail.ru"
