term="TuchkovAM"
name="Tuchkov A.M."
work="Ural Federal University, Beloyarsk NPP"
full_name="Tuchkov Andrey M."
regals="Deputy Chief Engineer, Beloyarsk NPP, Associate Professor, Departmentof Nuclear Power Plants and Renewable Energy Sources, Cand. Sci. (Engineering)"
email="tuchkov@belnpp.ru"
