term="TuchkovMY"
name="Tuchkov M.Yu."
work="Branch of JSC Rosenegroatom Concern, Novovoronezh Nuclear Power Plant"
full_name="Tuchkov Maxim Yu."
regals="Deputy Chief Engineer for Operations, Cand. Sci. (Engineering)"
email="TuchkovMU@nvnpp1.rosenergoatom.ru"
