term="UdalovaAA"
name="Udalova A.A."
work="IATE MEPhI, MEPhI"
full_name="Udalova Alla A."
regals="Professor, Department of Nuclear Physics and Technology, Dr. Sci. (Biology)"
email="oudalova@mail.ru"
