term="UgryumovAV"
name="Ugryumov A.V."
work="TVEL JSC"
full_name="Ugryumov Alexander V."
regals="Senior Vice President for Scientific and Technical Activities, Cand. Sci. (Engineering)"
email="AVUgryumov@tvel.ru"
