term="VarfolomeevaVA"
name="Varfolomeeva V.A."
work="JSC “All-Russian Research Institute for Nuclear Power Plants Operation”"
full_name="Varfolomeeva Valeria A."
regals="1st Category Engineer"
email="VAVarfolomeeva@vniiaes.ru"
