term="VasilyevAV"
name="Vasiliev A.V."
work="Institute of Industrial Ecology of Ural Branch of RAS"
full_name="Vasiliev Aleksey Vladimirovich"
regals="Head of Laboratory, Cand. Sci. (Engineering)"
email="alexey.vasiljev@gmail.com"