term="VasilyevaSY"
name="Vasilyeva S.Y."
work="Novovoronezh Polytechnic Institute of MEPhI"
full_name="Vasilyeva Svetlana Y."
regals="Senior lecturer, Cand. Sci. (Chemistry)"
email="SYVasileva@mephi.ru"
