term="VasiaevAV"
name="Vasiaev A.V."
work="Afrikantov OKBM JSC"
full_name="Vasiaev Aleksei V."
regals="Deputy General Director, Deputy General Designer. Head of the BN-1200 Project Responsibility Center"
email="vasyaev@okbm.nnov.ru"
