term="VasilyevBA"
name="Vasilyev B.A."
work="Afrikantov OKBM JSC"
full_name="Vasilyev Boris A."
regals="Advisor to the General Director for the Fast Reactor Fuel Cycle, Cand.Sci. (Engineering)"
email="bavasiliev@okbm.nnov.ru"
