term="VinnitskiiVA"
name="Vinnitskii V.A."
work="Saint-Petersburg State Institute of Technology (Technical University)"
full_name="Vinnitskii Vadim A."
regals="associate professor of the department of engineering radioecologyand radiochemical technology, Cand. Sci. (Engineering)"
email="ivinnicciy@gmail.com"
