term="YaurovSV"
name="Yaurov S.V."
work="Branch of JSC Rosenegroatom Concern, Novovoronezh Nuclear Power Plant"
full_name="Yaurov Sergey V."
regals="Chief Technologist"
email="YaurovSV@nvnpp1.rosenergoatom.ru"
