term="ZamiusskiyVN"
name="Zamiusskiy V.N."
work="JSC “Scientific and Technical Center “DIAPROM” (JSC “STCD”)"
full_name="Zamiusskiy Vladimir N."
regals="Head of the laboratory for the development of software and hardware for LMS, Cand. Sci. (Engineering)"
email="zamiussky@diaprom.ru"
