term="ZaryuginDG"
name="Zaryugin D.G."
work="Rosatom State Corporation"
full_name="Zaryugin Denis G."
regals="Project Manager of the Project Office, Cand. Sci. (Engineering)"
email="DGZaryugin@rosatom.ru"
