term="ZavadskiiDI"
name="Zavadskii D.I."
work="Beloyarsk NPP, Ural Federal University"
full_name="Zavadskii Daniil I."
regals="Leading Engineer of Unit Control of Beloyarsk NPP, Postgraduate Student"
email="danilezavadsky@gmail.com"
