term="ZolotukhinII"
name="Zolotukhin I.I."
work="MEPhI"
full_name="Zolotukhin Ivan I."
regals="1nd year Master’s Course Student, Department of Closed Nuclear Fuel Cycle Technologies"
email="zolivan123@mail.ru"
